<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Azza Indah Kusumastuti">
<meta name="dcterms.date" content="2024-01-23">

<title>Pengaruh Nilai Ekspor Migas terhadap Neraca Perdagangan Indonesia Tahun 2018-2022</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Nilai Ekspor Migas terhadap Neraca Perdagangan Indonesia Tahun 2018-2022</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Azza Indah Kusumastuti </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 23, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Dalam perdagangan internasional terdapat kegiatan ekspor dan impor antar negara yang saling membutuhkan komoditas dan jasa dalam kegiatan perekonomian internasional. Ekspor adalah pembelian negara lain atas barang buatan perusahaan-perusahaan di dalam negeri. Faktor terpenting yang menentukan ekspor adalah kemampuan dari Negara tersebut untuk mengeluarkan barangbarang yang dapat bersaing dalam pasaran luar negeri. (Sukirno, 2008: 205). Ekspor akan secara langsung mempengaruhi pendapatan nasional. Akan tetapi, hubungan yang sebaliknya tidak selalu berlaku, yaitu kenaikan pendapatan nasional belum tentu menaikkan ekspor oleh karena pendapatan nasional dapat mengalami kenaikan sebagai akibat dari kenaikan pengeluaran rumah tangga, investasi perusahaan, pengeluaran pemerintah dan penggantian barang impor dengan barang buatan dalam negeri.(Sukirno, 2008:206).</p>
<p>Neraca perdagangan merupakan salah satu komponen penting dari neraca transaksi berjalan yang mencatat arus ekspor dan impor barang yang biasanya di nyatakan dalam dolar AS. Hal yang sama dikemukakan oleh Pujoalwanto (2014) menjelaskan neraca perdagangan adalah suatu catatan atau ikhtisar yang memuat atau mencatat semua transaksi ekspor dan transaksi impor barang suatu Negara. Ekspor barang di catat di sisi kredit sedangkan impor barang dicatat di sisi debit, pada neraca perdagangan biasanya di bedakan antara ekspor dan impor primer (pertambangan dan pertanian) dengan ekspor dan impor non primer. Dalam prakteknya di Indonesia, neraca perdagangan ini dibagi menjadi dua jenis yaitu impor-ekspor migas dan impor-ekspor nonmigas. Neraca perdagangan dikatakan defisit bila nilai ekspor yang lebih kecil dari impornya dan dikatakan surplus bila ekspor barang lebih besar dari impornya dan dikatakan neraca perdagangan yang&nbsp; berimbang jika nilai ekspor suatu negara sama dengan nilai impor yang dilakukan negara tersebut, peningkatan ekspor akan berdampak terhadap meningkatnya neraca perdagangan, dan sebaliknya.</p>
<p>Ekspor migas adalah penjualan barang minyak dan gas Indonesia ke negara&nbsp;&nbsp; lain&nbsp;&nbsp; dalam&nbsp;&nbsp; bentuk&nbsp;&nbsp; dolar.&nbsp;&nbsp; Ini&nbsp;&nbsp; termasuk&nbsp;&nbsp; produk&nbsp;&nbsp; minyak&nbsp;&nbsp; yang dihasilkan,&nbsp; minyak&nbsp; mentah&nbsp; yang&nbsp; dihasilkan&nbsp; dari&nbsp; penambangan,&nbsp; gas&nbsp; elpiji dan&nbsp; gas&nbsp; lainnya&nbsp; yang&nbsp; dihasilkan,&nbsp; dan&nbsp; gas&nbsp; alam&nbsp; yang&nbsp; dihasilkan&nbsp; dari penambangan. Indonesia merupakan salah satu negara penghasil migas di dunia. Peningkatan ekspor Indonesia secara kumulatif didorong oleh ekspor migas yang masih tumbuh sangat tinggi dan menunjukkan pertumbuhan yang konsisten disebabkan oleh faktor volume akibat peningkatan permintaan dari beberapa negara tujuan utama serta pengaruh harga komoditas.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Ruang lingkup penelitian ini terdapat 2 variabel antara lain nilai ekspor migas Indonesia dan neraca perdagangan Indonesia. Data yang digunakan adalah data yang bersifat time series yaitu dalam kurun waktu 2018-2022 dengan satuan yang telah diubah ke dalam USD guna untuk memudahkan penyetaraan mata uang secara internasional, data inilah yang kemudian menjadi objek penelitian.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<p>Berdasarkan uraian latar belakang diatas maka yang menjadi masalah pokok pada penelitian ini adalah:</p>
<ol type="1">
<li>Apakah ekspor migas mempengaruhi neraca perdagangan Indonesia?</li>
<li>Bagaimana hubungan antara ekspor migas denga neraca perdagangan Indonesia?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan penelitian ini untuk mengetahui pengaruh ekspor migas terhadap neraca perdagangan Indonesia dan hubungan antara keduanya di tahun terkait.</p>
<p>Manfaat penelitian ini agar masyarakat mengerti bahwa adanya pengaruh ekspor migas terhadap neraca perdagangan Indonesia dan bagaimana hubungan ekspor migas terhadap neraca perdagangan Indonesia.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Ini tidak wajib ada di tulisan anda tapi anda dapat menunjukkan Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p>Tujuan&nbsp; ekspor&nbsp; komoditas&nbsp; minyak&nbsp; dan&nbsp; gas&nbsp; Indonesia&nbsp; adalah&nbsp; untuk meningkatkan&nbsp; ekonomi&nbsp; bangsa&nbsp; dan&nbsp; memperluas&nbsp; pasar&nbsp; domestik&nbsp; dan internasional. Menurut&nbsp;&nbsp; Undang-Undang&nbsp;&nbsp; Nomor&nbsp;&nbsp; 22&nbsp;&nbsp; Tahun&nbsp;&nbsp; 2001 Tentang&nbsp; Minyak&nbsp; dan&nbsp; Gas&nbsp; Bumi&nbsp; Pasal&nbsp; 1angka&nbsp; 1&nbsp; dalam&nbsp; Fajar&nbsp; (2013:3) Menyebutkan bahwa:Minyak&nbsp; Bumi&nbsp; adalah&nbsp; hasil&nbsp; proses&nbsp; alami&nbsp; berupa&nbsp; hidrokarbon yang&nbsp; dalam&nbsp; kondisi&nbsp; tekanan&nbsp; dan&nbsp; temperatur&nbsp; atmosfer&nbsp; berupa fasa cair atau padat, termasuk aspal, lilin mineral atau ozokerit, dan&nbsp; bitumen&nbsp; yang&nbsp; diperoleh&nbsp; dari&nbsp; proses&nbsp; penambangan,&nbsp; tetapi tidak&nbsp; termasuk&nbsp; batu&nbsp; bara&nbsp; atau&nbsp; endapan&nbsp; hidrokarbon&nbsp; lain&nbsp; yang berbentuk&nbsp;&nbsp; padat&nbsp;&nbsp; yang&nbsp;&nbsp; diperoleh&nbsp;&nbsp; dari&nbsp;&nbsp; kegiatan&nbsp;&nbsp; yang&nbsp;&nbsp; tidak berkaitan&nbsp;&nbsp; dengan&nbsp;&nbsp; kegiatan&nbsp;&nbsp; usaha&nbsp;&nbsp; Minyak&nbsp;&nbsp; dan&nbsp;&nbsp; Gas&nbsp;&nbsp; Bumi. Pengertian&nbsp;&nbsp; Gas&nbsp;&nbsp; Bumi&nbsp;&nbsp; menurut&nbsp;&nbsp; Undang-Undang&nbsp;&nbsp; Nomor&nbsp;&nbsp; 22 Tahun&nbsp; 2001&nbsp; Tentang&nbsp; Minyak&nbsp; dan&nbsp; Gas&nbsp; Bumi&nbsp; Pasal&nbsp; 1&nbsp; angka&nbsp; 2 Menyebutkan&nbsp; bahwa&nbsp; :&nbsp; “Gas&nbsp; Bumi&nbsp; adalah&nbsp; hasil&nbsp; proses&nbsp; alami berupa&nbsp;&nbsp;&nbsp; hidrokarbon&nbsp;&nbsp;&nbsp; yang&nbsp;&nbsp;&nbsp; dalam&nbsp;&nbsp;&nbsp; kondisi&nbsp;&nbsp;&nbsp; tekanandan temperatur atsmofer berupa fasa gas yang diperoleh dari proses penambangan Minyak dan Gas Bumi.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Tahun</th>
<th style="text-align: center;">Nilai Ekspor Migas (X)</th>
<th style="text-align: center;">Neraca Perdagangan (Y)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">2018</td>
<td style="text-align: center;">17.171,7</td>
<td style="text-align: center;">-12.697,10</td>
</tr>
<tr class="even">
<td style="text-align: center;">2019</td>
<td style="text-align: center;">11.789,3</td>
<td style="text-align: center;">-10.096,10</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2020</td>
<td style="text-align: center;">8.251,1</td>
<td style="text-align: center;">-6.005,70</td>
</tr>
<tr class="even">
<td style="text-align: center;">2021</td>
<td style="text-align: center;">12.247,4</td>
<td style="text-align: center;">-13.281,70</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2021</td>
<td style="text-align: center;">15.998,2</td>
<td style="text-align: center;">-24.418,10</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">'C:/Users/Azza Indah K/OneDrive/AZZA INDAH K/METOPEN UAS INDIVIDU'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'readxl'</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'Nilai Ekspor dan Neraca Perdagangan Migas.xlsx'</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X,<span class="at">data=</span>dat)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>u<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>X,dat<span class="sc">$</span>u,<span class="at">xlab=</span><span class="st">"Nilai Ekspor Migas"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span> (<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Plot Pengaruh Error Terhadap Nilai Ekspor Migas (X)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'readxl'</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'Nilai Ekspor dan Neraca Perdagangan Migas.xlsx'</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X,<span class="at">data=</span>dat)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>u<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>X,dat<span class="sc">$</span>u,<span class="at">xlab=</span><span class="st">"Neraca Perdagangan"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Plot Pengaruh Error Terhadap Neraca Perdagangan (Y)</p>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode yang dipilih adalah regresi univariat atau Ordinary Least Square (OLS) dengan 1 variabel independen. Penelitian ini merbaksud mencari hubungan antara Nilai Ekspor Migas dan Neraca Perdagangan. Spesifikasi yang dilakukan adalah:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah Y dan <span class="math inline">\(x_t\)</span> adalah X. Y adalah Neraca Perdagangan dan X adalah Nilai Ekspor Migas.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<table class="table">
<thead>
<tr class="header">
<th>Variable</th>
<th style="text-align: center;">Coefficient</th>
<th style="text-align: center;">Std. Error</th>
<th style="text-align: center;">t- value</th>
<th style="text-align: center;">Prob(.)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td style="text-align: center;">4542.5261</td>
<td style="text-align: center;">10513.4990</td>
<td style="text-align: center;">0.430</td>
<td style="text-align: center;">0.696</td>
</tr>
<tr class="even">
<td>X</td>
<td style="text-align: center;">-1.3616</td>
<td style="text-align: center;">0.7802</td>
<td style="text-align: center;">-1.745</td>
<td style="text-align: center;">0.179</td>
</tr>
<tr class="odd">
<td>R squarred</td>
<td style="text-align: center;">0.5038</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td>Adjusted R squared</td>
<td style="text-align: center;">0.3383</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td>F- Statistic</td>
<td style="text-align: center;">3.045</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td>Prob (F- Statistic)</td>
<td style="text-align: center;">0.1793</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<p>Hasil regresi yang diperoleh dimasukan ke dalam persamaan rumus, sehingga rumusnya menjadi :<span class="math display">\[Y = 4542.5261 + (-1.3616X)\]</span></p>
<p>Nilai Ekspor Migas tidak berperan positif dalam neraca perdagangan karena setiap 1 nilai ekspor bertambah itu berpengaruh negatif terhadap neraca perdagangan.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X,<span class="at">data=</span>dat)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X, data = dat)

Residuals:
      1       2       3       4       5 
 6158.1  1430.5   703.4 -1131.3 -7160.7 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)  4525.5261 10513.4990   0.430    0.696
X              -1.3616     0.7802  -1.745    0.179

Residual standard error: 5568 on 3 degrees of freedom
Multiple R-squared:  0.5038,    Adjusted R-squared:  0.3383 
F-statistic: 3.045 on 1 and 3 DF,  p-value: 0.1793</code></pre>
</div>
</div>
<p>Dapat dilihat dari tabel di atas bahwa ketika nilai ekspor migas (X) adalah nol,diperkirakan neraca perdagangan (Y) akan naik sekitar 4525.53. Sedangkan jika nilai ekspor migas mengalami kenaikan 1, neraca perdagangan mengalami penurunan sebesar 1.3616.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Setelah dilakukan penelitian melalui sistem regresi univariat atau OLS (Ordinary Least Square),maka dapat disimpulkan bahwa nilai ekspor migas berpengaruh negatif terhadap neraca perdagangan dan sebaliknya. Dikarenakan jika nilai ekspor migas naik, neraca perdagangan mengalami penurunan.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Khalwat Asyaria, -&nbsp;and&nbsp;Risanda A. Budiantoro, -&nbsp;and&nbsp;Sri Herianingrum, -&nbsp;(2020)&nbsp;<em>Analisis Neraca Perdagangan Migas dan Non Migas Terhadap Volatilitas Cadangan Devisa Di Indonesia, 1975-2016.</em>&nbsp;Jurnal Manajemen dan Bisnis Indonesia, 6 (1). pp.&nbsp;38-45. ISSN pISSN: 2443-2830, eISSN: 2460-9471</p>
<p><em>Rizquna : Jurnal Hukum dan Ekonomi SyariahVolume 1, Nomor 4, April-Juni2023. ISSN 2962-3057 (Online) dan ISSN 29623847(Cetak) <a href="https://journal.citradharma.org/index.php/rizquna" class="uri">https://journal.citradharma.org/index.php/rizquna</a></em></p>
<p><em>DOI: <a href="https://doi.org/10.56480/rizquna.v1i4/880" class="uri">https://doi.org/10.56480/rizquna.v1i4/880</a></em></p>
<p>Kinerja Ekspor dan Impor Terus Menguat, Neraca Perdagangan Indonesia Tercatat Surplus 29 Bulan Berturut-Turut</p>
<p><a href="https://www.kemenkeu.go.id/informasi-publik/publikasi/berita-utama/surplus-neraca-perdagangan" class="uri">https://www.kemenkeu.go.id/informasi-publik/publikasi/berita-utama/surplus-neraca-perdagangan</a></p>
<p>Neraca Perdagangan Indonesia</p>
<p><a href="https://satudata.kemendag.go.id/data-informasi/perdagangan-luar-negeri/neraca-perdagangan-indonesia" class="uri">https://satudata.kemendag.go.id/data-informasi/perdagangan-luar-negeri/neraca-perdagangan-indonesia</a></p>
<p>Nilai Ekspor dan Impor Migas (juta US$) 1996-2022</p>
<p><a href="https://www.bps.go.id/id/statistics-table/1/MTAwNCMx/nilai-ekspor-dan-impor-migas--juta-us---1996-2022.html" class="uri">https://www.bps.go.id/id/statistics-table/1/MTAwNCMx/nilai-ekspor-dan-impor-migas--juta-us---1996-2022.html</a></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>